AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Card-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Tracing: Active
    Environment:
      Variables:
        EVENT_BUS_ARN:
          Fn::ImportValue:
            !Sub "common-service-${Stage}-MTGEventBus"
        #update frequency in days
        CARDS_UPDATE_FREQUENCY: "7"

Parameters:
  Stage:
    Type: String
    Default: development

Resources:
#  MTGCardApi:
#    Type: AWS::Serverless::Api
#    Properties:
#      Name: !Sub "${Stage}-mtg-card-api"
#      StageName: !Ref Stage
#      OpenApiVersion: '2.0'
#      DefinitionBody:
#        Fn::Transform:
#          Name: AWS::Include
#          Parameters:
#            Location: ./swagger-spec.json
#      MethodSettings:
#        - ResourcePath: '/*'
#          HttpMethod: '*'
#          LoggingLevel: INFO
#          MetricsEnabled: true
#      AccessLogSetting:
#        DestinationArn: !GetAtt AccessLogGroup.Arn
#        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","routeKey":"$context.routeKey","status":$context.status,"responseLatency":$context.responseLatency}'

  AccessLogGroup:
    Type: AWS::Logs::LogGroup

  MTGCardDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: RemoveAt
        Enabled: true
      BillingMode: PAY_PER_REQUEST

  renewEntitiesRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Rule to trigger RenewEntitiesFunction, to renew the card database"
      Name: !Sub "${Stage}-renew-entities-rule"
      ScheduleExpression: "cron(0 4 * * ? *)"
      Targets:
        - Arn: !GetAtt RenewEntitiesFunction.Arn
          Id: !Sub "${Stage}-renew-entities-rule-target"

  RenewEntitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/renewEntities
      MemorySize: 500
      Timeout: 180
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref MTGCardDynamoDBTable
      Policies:
        - AmazonDynamoDBFullAccess

  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Stage}-scheduler--trigger-function-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "scheduler.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${Stage}-InvokeLambdaFunctionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action: "lambda:InvokeFunction"
                Effect: "Allow"
                Resource: !GetAtt RenewEntitiesFunction.Arn

  CardSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      FlexibleTimeWindow:
        Mode: 'OFF'
      ScheduleExpression: "cron(0 5 * * ? *)"
      ScheduleExpressionTimezone: "GMT+1"
      Target:
        Arn: !GetAtt RenewEntitiesFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn

#Outputs:
#  MTGCardApiUrl:
#    Description: "API Gateway endpoint URL"
#    Value: !Sub "https://${MTGCardApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
#  MTGCardApi:
#    Description: "Api gateway"
#    Value: !Ref MTGCardApi
#    Export:
#      Name:
#        'Fn::Sub': '${AWS::StackName}-api'
