# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "cnsdm-eindopdracht-3-front-end"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "cnsdm-eindopdracht-3-front-end-development"
s3_prefix = "cnsdm-eindopdracht-3-front-end-development"
parameter_overrides = "Stage=\"development\""
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
region = "us-east-1"
confirm_changeset = true
image_repositories = []

[staging.deploy.parameters]
stack_name = "cnsdm-eindopdracht-3-front-end-staging"
s3_prefix = "cnsdm-eindopdracht-3-front-end-staging"
parameter_overrides = "Stage=\"staging\""
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
region = "us-east-1"
confirm_changeset = true
image_repositories = []

[production.deploy.parameters]
stack_name = "cnsdm-eindopdracht-3-front-end-production"
s3_prefix = "cnsdm-eindopdracht-3-front-end-production"
parameter_overrides = "Stage=\"production\""
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
region = "us-east-1"
confirm_changeset = true
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
