AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: frontend stack

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  Stage:
    Type: String
  FrontEndStack:
    Type: String
    Default: front-end

Resources:
  FrontEndS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontEndS3BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Stage}/frontEnd/bucketName
      Type: String
      Value: !Ref FrontEndS3Bucket

  FrontEndS3Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontEndS3Bucket
      PolicyDocument:
        Id: PolicyForCloudFrontPrivateContent
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FrontEndS3Bucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFront}

#  WebAppOriginAccessControl:
#    Type: AWS::CloudFront::OriginAccessControl
#    Properties:
#      OriginAccessControlConfig:
#        Name: !Sub "${Stage}-front-end-origin-access-control"
#        OriginAccessControlOriginType: s3
#        SigningBehavior: always
#        SigningProtocol: sigv4

#  CloudFront:
#    Type: AWS::CloudFront::Distribution
#    Properties:
#      DistributionConfig:
#        Enabled: true
#        DefaultRootObject: "index.html"
#        Origins:
#          - Id: !Sub ${Stage}-front-end
#            DomainName: !GetAtt FrontEndS3Bucket.DomainName
#            OriginAccessControlId: !GetAtt WebAppOriginAccessControl.Id
#            CustomOriginConfig:
#              OriginProtocolPolicy: https-only
#        DefaultCacheBehavior:
#          TargetOriginId: !Sub ${Stage}-front-end
#          AllowedMethods:
#            - GET
#            - HEAD
#            - OPTIONS
#            - PUT
#            - PATCH
#            - POST
#            - DELETE
#          CachedMethods:
#            - GET
#            - HEAD
#          ViewerProtocolPolicy: redirect-to-https
#          ForwardedValues:
#            QueryString: true
#        CustomErrorResponses:
#          - ErrorCode: 404
#            ResponsePagePath: /index.html
#            ErrorCachingMinTTL: 30
#            ResponseCode: 200

Outputs:
  FrontEndS3BucketDomainName:
    Description: Front-end S3 bucket domain name
    Value: !GetAtt FrontEndS3Bucket.DomainName
    Export:
      Name: !Sub ${AWS::StackName}-FrontEndS3BucketDomainName
