AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: monitoring-service

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  Stage:
    Type: String
    Default: development

Resources:
  DragonDashboard:
    Type: 'AWS::CloudWatch::Dashboard'
    Properties:
      DashboardName: !Sub 'Dragon-Dashboard-${Stage}'
      DashboardBody: !Sub
        - '{
              "widgets": [
                {
                  "type": "text",
                  "x": 0,
                  "y": 0,
                  "width": 24,
                  "height": 2,
                  "properties": {
                      "markdown": "# Summary\n## Api`s \n"
                  }
                },
                {
                  "type": "text",
                  "x": 0,
                  "y": 7,
                  "width": 24,
                  "height": 1,
                  "properties": {
                    "markdown": "## Cloudfront\n"
                  }
                },
                {
                "type": "text",
                "x": 0,
                "y": 18,
                "width": 24,
                "height": 1,
                "properties": {
                  "markdown": "## Import Scryfall data\n"
                  }
                },
                {
                  "height": 5,
                  "width": 9,
                  "y": 2,
                  "x": 0,
                  "type": "metric",
                  "properties": {
                    "metrics": [
                      [ { "expression": "FILL(METRICS(),0)", "label": "", "region": "${AWS::Region}" } ],
                      [ "AWS/ApiGateway", "Count", "ApiName", "${Stage}-mtg-user-api", { "region": "${AWS::Region}", "visible": false, "label": "User-Api" } ],
                      [ "...", "${Stage}-mtg-wishlist-api", { "region": "${AWS::Region}", "visible": false, "label": "Wishlist-Api" } ],
                      [ "...", "${Stage}-mtg-collection-api", { "region": "${AWS::Region}", "visible": false, "label": "Collection-Api" } ],
                      [ "...", "${Stage}-mtg-deck-api", { "region": "${AWS::Region}", "visible": false, "label": "Deck-Api" } ],
                      [ "...", "${Stage}-mtg-card-api", { "region": "${AWS::Region}", "visible": false, "label": "Card-Api" } ]
                    ],
                    "view": "timeSeries",
                    "title": "Api - All Requests (per 5 mins)",
                    "region": "${AWS::Region}",
                    "stat": "SampleCount",
                    "period": 300,
                    "setPeriodToTimeRange": false,
                    "stacked": false,
                    "sparkline": true,
                    "trend": true,
                    "liveData": true,
                    "legend": {
                      "position": "bottom"
                    },
                    "yAxis": {
                      "left": {
                          "label": "Amount",
                          "showUnits": false
                      }
                    }
                  }
                },
                {
                  "height": 5,
                  "width": 9,
                  "y": 2,
                  "x": 15,
                  "type": "metric",
                  "properties": {
                    "metrics": [
                      [
                        {
                          "expression": "FILL(METRICS(),0)",
                          "label": "",
                          "region": "${AWS::Region}"
                        }
                      ],
                      ["AWS/ApiGateway", "Latency", "ApiName", "${Stage}-mtg-user-api", { "region": "${AWS::Region}", "visible": false, "label": "User-Api" } ],
                      ["...", "${Stage}-mtg-wishlist-api", {"label": "Wishlist-Api", "visible": false, "region": "${AWS::Region}"}],
                      ["...", "${Stage}-mtg-collection-api", {"label": "Collection-Api", "visible": false, "region": "${AWS::Region}"}],
                      ["...", "${Stage}-mtg-deck-api", {"label": "Deck-Api", "visible": false, "region": "${AWS::Region}"}],
                      ["...", "${Stage}-mtg-card-api", {"label": "Card-Api", "visible": false, "region": "${AWS::Region}"}]
                    ],
                    "view": "timeSeries",
                    "stacked": false,
                    "region": "${AWS::Region}",
                    "period": 300,
                    "stat": "Average",
                    "title": "Api - Average Latency (per 5 mins)",
                    "yAxis": {
                      "left": {
                          "label": "milliseconds",
                          "showUnits": false
                      }
                    }
                  }
                },
                {
                  "height": 5,
                  "width": 9,
                  "y": 8,
                  "x": 0,
                  "type": "metric",
                  "properties": {
                    "metrics": [
                      [
                        {
                          "expression": "FILL(METRICS(),0)",
                          "label": "",
                          "region": "${AWS::Region}"
                        }
                      ],
                      [ "AWS/CloudFront", "Requests", "Region", "Global", "DistributionId", "${CloudFrontDistributionId}", { "region": "${AWS::Region}", "visible": false } ]
                    ],
                    "view": "timeSeries",
                    "title": "Cloudfront - All Requests (per 5 mins)",
                    "region": "${AWS::Region}",
                    "stat": "Sum",
                    "period": 300,
                    "setPeriodToTimeRange": false,
                    "stacked": false,
                    "sparkline": true,
                    "trend": true,
                    "liveData": true,
                    "legend": {
                      "position": "bottom"
                    },
                    "yAxis": {
                      "left": {
                          "label": "Amount",
                          "showUnits": false
                      }
                    }
                  }
                },
                {
                  "height": 5,
                  "width": 6,
                  "y": 2,
                  "x": 9,
                  "type": "metric",
                  "properties": {
                    "metrics": [
                      [ { "expression": "FILL(100*METRICS(), 0)", "label": "", "region": "${AWS::Region}" }],
                      ["AWS/ApiGateway", "5XXError", "ApiName", "${Stage}-mtg-user-api", {"label": "User-Api", "visible": false, "region": "${AWS::Region}"}],
                      ["...", "${Stage}-mtg-wishlist-api", {"label": "Wishlist-Api", "visible": false, "region": "${AWS::Region}"}],
                      ["...", "${Stage}-mtg-collection-api", {"label": "Collection-Api", "visible": false, "region": "${AWS::Region}"}],
                      ["...", "${Stage}-mtg-deck-api", {"label": "Deck-Api", "visible": false, "region": "${AWS::Region}"}],
                      ["...", "${Stage}-mtg-card-api", {"label": "Card-Api", "visible": false, "region": "${AWS::Region}"}]
                    ],
                    "view": "timeSeries",
                    "stacked": false,
                    "region": "${AWS::Region}",
                    "stat": "Average",
                    "title": "Api - Total Errors (per 5 mins)",
                    "period": 300,
                    "yAxis": {
                      "left": {
                          "label": "%",
                          "showUnits": false
                      }
                    }
                  }
                },
                {
                  "height": 5,
                  "width": 6,
                  "y": 8,
                  "x": 9,
                  "type": "metric",
                  "properties": {
                    "metrics": [
                      [ { "expression": "FILL(METRICS(), 0)", "label": "", "region": "${AWS::Region}" } ],
                      [ "AWS/CloudFront", "TotalErrorRate", "Region", "Global", "DistributionId", "${CloudFrontDistributionId}", { "visible": false, "region": "${AWS::Region}" } ]
                    ],
                    "view": "timeSeries",
                    "stacked": false,
                    "region": "${AWS::Region}",
                    "stat": "Average",
                    "title": "Cloudfront - Total Errors (per 5 mins)",
                    "period": 300,
                    "yAxis": {
                      "left": {
                          "label": "%",
                          "showUnits": false
                      }
                    }
                  }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 19,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "metrics": [
                            [ "AWS/Lambda", "Invocations", "FunctionName", "d", { "region": "us-east-1", "yAxis": "left" } ]
                        ],
                        "view": "timeSeries",
                        "stacked": false,
                        "region": "us-east-1",
                        "period": 300,
                        "stat": "Sum",
                        "start": "-PT3H",
                        "title": "Import Scryfall data invocations"
                    }
                }
              ]
            }'
        - CloudFrontDistributionId: !ImportValue
            'Fn::Sub': "front-end-${Stage}-CloudFrontId"

