AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: common-service

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  Stage:
    Type: String
    Default: staging

Resources:


Outputs:
  MTGEventBus:
    Description: "Event bus"
    Value: !Ref MTGEventBus
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-MTGEventBus'
