# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "user-service"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = false
resolve_s3 = true
s3_prefix = "sam-user-development"
region = "us-east-1"

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = false
resolve_s3 = true
s3_prefix = "sam-user-staging"
region = "us-east-1"
parameter_overrides = "Stage=\"staging\""

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = false
resolve_s3 = true
s3_prefix = "common-service-production"
region = "us-east-1"
parameter_overrides = "Stage=\"production\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
