AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: user-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64
    Tracing: Active

Parameters:
  MTGApiGatewayId:
    Type: String
    Default: '7sscdg19c6'

Resources:
  ApiGatewayIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "lambda:*"
                Resource: 
                  - !GetAtt HelloWorld2Function.Arn
                  - !GetAtt RegisterUserFunction.Arn

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MTGUserPool
      EmailVerificationSubject: Please verify your email address
      EmailVerificationMessage: "Hello {username},\n\nPlease click the following link to verify your email: {link}"
      Policies:
        PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
      Schema:
        - Name: email
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: MTGUserPoolClient

  RegisterUserIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MTGApiGatewayId
      Description: Register User Integration
      ConnectionType: INTERNET
      CredentialsArn: !GetAtt ApiGatewayIamRole.Arn
      PassthroughBehavior: WHEN_NO_MATCH
      TimeoutInMillis: 29000
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterUserFunction.Arn}/invocations"

  RegisterUserRoute:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - RegisterUserFunction
    Properties:
      ApiId: !Ref MTGApiGatewayId
      RouteKey: POST /users/new
      Target: !Join
        - /
        - - integrations
          - !Ref RegisterUserIntegration

  RegisterUserFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: RegisterUserFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cognito-idp:AdminCreateUser"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "cognito-idp:AdminInitiateAuth"
                Resource: "*"

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RegisterUserFunction
      CodeUri: functions/register_user/
      Role: !Ref RegisterUserFunctionIamRole
      Environment:
        Variables:
          USER_POOL_CLIENT_ID: !Ref UserPoolClient

  HelloWorld2Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MTGApiGatewayId
      Description: Test Integration
      ConnectionType: INTERNET
      CredentialsArn: !GetAtt ApiGatewayIamRole.Arn
      PassthroughBehavior: WHEN_NO_MATCH
      TimeoutInMillis: 29000
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorld2Function.Arn}/invocations"

  HelloWorld2Route:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - HelloWorld2Function
    Properties:
      ApiId: !Ref MTGApiGatewayId
      RouteKey: GET /hello2
      Target: !Join
        - /
        - - integrations
          - !Ref HelloWorld2Integration

  HelloWorld2FunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
  
  HelloWorld2Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello_world/
      Role: !GetAtt HelloWorld2FunctionIamRole.Arn

Outputs:
  UserPoolClientId:
    Description: UserPool Client Id
    Value: !Ref UserPoolClient
  HelloWorld2Function:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorld2Function.Arn
  HelloWorld2FunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorld2FunctionIamRole.Arn
