# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = false
resolve_s3 = true
stack_name = "collection-service-development"
s3_prefix = "collection-service-development"
region = "us-east-1"
parameter_overrides = [
    "Stage=development",
    "CommonStack=common-service-development",
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = false
resolve_s3 = true
stack_name = "collection-service-staging"
s3_prefix = "collection-service-staging"
region = "us-east-1"
parameter_overrides = [
    "Stage=staging",
    "CommonStack=common-service-staging",
]

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = false
resolve_s3 = true
stack_name = "collection-service-production"
s3_prefix = "collection-service-production"
region = "us-east-1"
parameter_overrides = [
    "Stage=production",
    "CommonStack=common-service-production",
]
