name: Build a custom dev environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment name for the stack
        required: true
        type: string

jobs:
  deploy-backend-services:
    uses: ./.github/workflows/deploy-all-backend-services.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-front-end:
    needs: deploy-backend-services
    uses: ./.github/workflows/release-front-end-pipeline.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
