name: Release and deploy the card bounded context

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "card/**"
      - ".github/workflows/card-context-release-pipeline.yml"

defaults:
  run:
    working-directory: "./card"

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v3
    
          - name: Set up Python 3.9
            uses: actions/setup-python@v4
            with:
              python-version: 3.9
    
          - name: Set up SAM CLI
            uses: aws-actions/setup-sam@v2
    
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1-node16
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
              aws-region: us-east-1
              
          - name: Build the serverless application
            run: sam build
    
          - name: Deploy the serverless application
            run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
    
          - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            with:
              tag_name: v${{ github.run_number }}
              release_name: v${{ github.run_number }}
              draft: false
              prerelease: false
    