name: Test and release back-end services

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-common-service:
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      path: ./common-service
      service-name: common-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-card-service:
    needs: deploy-common-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      path: ./card-service
      service-name: card-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-collection-service:
    needs: deploy-common-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      path: ./collection-service
      service-name: collection-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-deck-service:
    needs: deploy-common-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      path: ./deck-service
      service-name: deck-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-user-service:
    needs: deploy-common-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      path: ./user-service
      service-name: user-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-wishlist-service:
    needs: deploy-common-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      path: ./wishlist-service
      service-name: wishlist-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
