name: Feature pipeline test back-end services

on:
  push:
    branches:
     - feature/**
    paths:
      - 'user-service/**'
      - 'wishlist-service/**'
      - 'deck-service/**'
      - 'card-service/**'
      - 'collection-service/**'
  workflow_dispatch:

jobs:
  back-end-sonarQube-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: card
            path: ./card-service
          - service: user
            path: ./user-service
          - service: deck
            path: ./deck-service
          - service: wishlist
            path: ./wishlist-service
          - service: collection
            path: ./collection-service

    defaults:
      run:
        working-directory: ${ matrix.path }

    steps:
      - uses: actions/checkout@v4
      - name: Set Locale
        run: echo "export LC_ALL=C.UTF-8" >> $GITHUB_ENV

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build the serverless application
        run: sam build

      - name: Test the serverless application
        run: |
          pip3 install -r tests/test-requirements.txt
          coverage run --source=. -m pytest tests -rap --junitxml target/testreport-coverage.xml
          coverage xml -o target/coverage-${{ matrix.service }}.xml
