name: SonarQUbe scan of the front-end service

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
    secrets:
      sonarQube-token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js v15.X
        uses: actions/setup-node@v4
        with:
          node-version: 15.X

      - name: Install dependencies
        run: npm ci

      - name: Validate Typescript typings
        run: npm run type-check

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build the serverless application
        run: sam build
            
      - name: Build the web-application
        run: npm run build

      - name: Run tests and collect coverage
        run: |        
          npm run test:coverage
          npm run test:e2e

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ${{ inputs.path }}
        env:
          SONAR_TOKEN: ${{ secrets.sonarQube-token }}
          SONAR_HOST_URL: https://sonar.cloud-native-minor.it
