on:
  push:
    branches:
      - staging
      - master
    paths:
      - '/card/**'
  workflow_dispatch:


jobs:
  run-sonarQube-scan-on-card-service:
    if: github.ref == 'refs/heads/staging'
    uses: .github/workflows/back-end-sonarQube-scan.yml
    with:
      path: './card'
      service-name: 'card-service'
      sonarQube-token: ${{ secrets.SONAR_TOKEN_CARD_SERVICE }}
      coverage-file: 'coverage-card.xml'

  deploy-card-service-to-staging:
    uses: .github/workflows/release-pipeline.yml
    with:
      path: '/card/**'
      environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
