name: Deploy ${service-name} to ${environment}

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      environment:
        required: true
        type: string
      service-name:
        required: true
        type: string

defaults:
  run:
    working-directory: ${{ github.event.inputs.path }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build the serverless application
        run: sam build

      - name: Deploy the serverless application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env ${{ github.event.inputs.environment }}