on:
  push:
    branches:
      - staging
      - master
    paths:
      - '/user/**'
  workflow_dispatch:


jobs:
  run-sonarQube-scan-on-user-service:
    if: github.ref == 'refs/heads/staging'
    uses: .github/workflows/back-end-sonarQube-scan.yml
    with:
      path: './user'
      service-name: 'user-service'
      sonarQube-token: ${{ secrets.SONAR_TOKEN_USER_SERVICE }}
      coverage-file: 'coverage-user.xml'

  deploy-user-service-to-staging:
    uses: .github/workflows/release-pipeline.yml
    with:
      path: '/user/**'
      environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
