name: Test and release back-end services

on:
  push:
    branches:
     - staging
     - master
    paths:
      - '/user-service/**'
      - '/collection-service/**'
      - '/deck-service/**'
      - '/card-service/**'
      - '/common-service/**'
  workflow_dispatch:

jobs:
  back-end-sonarQube-matrix:
    if: github.ref == 'refs/heads/staging'
    strategy:
      matrix:
        include:
#          - service: card
#            sonarQubeSecret: SONAR_TOKEN_CARD_SERVICE
          - service: user-service
            sonarQubeSecret: SONAR_TOKEN_USER_SERVICE
#          - service: deck
#            sonarQubeSecret: SONAR_TOKEN_DECK_SERVICE
#          - service: collection
#            sonarQubeSecret: SONAR_TOKEN_COLLECTION_SERVICE
    uses: ./.github/workflows/back-end-sonarQube-scan.yml
    with:
      path: ./${{ matrix.service }}
      service-name: ${{ matrix.service }}
      coverage-file: coverage-${{ matrix.service }}.xml
    secrets:
      SONAR_QUBE_TOKEN: ${{ secrets[matrix.sonarQubeSecret] }}

  back-end-deployment-matrix-staging:
    needs: back-end-sonarQube-matrix
    if: github.ref == 'refs/heads/staging' && success()
    strategy:
      max-parallel: 1
      matrix:
        service: [ 'common-service', 'user-service' ]
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      path: ./${{ matrix.service }}
      service-name: ${{ matrix.service }}
      environment: staging

  back-end-deployment-matrix-production:
    if: github.ref == 'refs/heads/master'
    strategy:
      max-parallel: 1
      matrix:
        service: [ 'common-service', 'user-service' ]
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      path: ./${{ matrix.service }}
      service-name: ${{ matrix.service }}
      environment: production

  tag-and-release:
    needs: [back-end-deployment-matrix-staging, back-end-deployment-matrix-production]
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional job failed
        if: ${{ needs.back-end-deployment-matrix-staging.result == 'failure' || needs.back-end-deployment-matrix-production.result == 'failure' }}
        run: exit 1
      
      - name: Tag the build version
        run: |
          git tag "back-end-v${GITHUB_RUN_NUMBER}"
          git push origin "back-end-v${GITHUB_RUN_NUMBER}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: back-end-v${{ github.run_number }}
          release_name: back-end-v${{ github.run_number }}
          draft: false
          prerelease: false
