on:
  push:
    branches:
      - staging
      - master
    paths:
      - '/user/**'
      - '/collection/**'
      - '/deck/**'
      - '/card/**'
  workflow_dispatch:

jobs:
  back-end-sonarQube-matrix:
    if: github.ref == 'refs/heads/staging'
    strategy:
      matrix:
        include:
          - service: card
            sonarQubeSecret: SONAR_TOKEN_CARD_SERVICE
          - service: user
            sonarQubeSecret: SONAR_TOKEN_USER_SERVICE
          - service: deck
            sonarQubeSecret: SONAR_TOKEN_DECK_SERVICE
          - service: collection
            sonarQubeSecret: SONAR_TOKEN_COLLECTION_SERVICE
    uses: .github/workflows/back-end-sonarQube-scan.yml
    with:
      path: ./${{ matrix.service }}
      service-name: ${{ matrix.service }}-service
      coverage-file: coverage-${{ matrix.service }}.xml
    secrets:
      SONAR_QUBE_TOKEN: ${{ secrets[matrix.sonarQubeSecret] }}

  back-end-deployment-matrix:
    if: (github.ref == 'refs/heads/staging' && success()) || github.ref == 'refs/heads/master'
    strategy:
      matrix:
        service: [ 'user', 'collection', 'deck', 'card' ]
    uses: .github/workflows/release-back-end-pipeline.yml
    with:
      path: ./${{ matrix.service }}
      service-name: ${{ matrix.service }}-service
      environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}