name: Deploy webapplication to proper environment

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      environment:
        required: true
        type: string
      s3-bucket-name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

defaults:
  run:
    working-directory: ${{ inputs.path }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.X]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm ci

      - name: Production build
        run: |
          unset CI
          npm run build --omit dev

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Retrieve SSM parameter
        id: parameters
        run: |
          echo "bucket_name=$(aws ssm get-parameter --name="/${{ inputs.environment }}/frontEnd/bucketName" --output json | jq '.Parameter.Value' -r)" >> $GITHUB_OUTPUT
#          echo "cloudfront_id=$(aws ssm get-parameter --name="/staging/frontEnd/cloudFrontId" --output json | jq '.Parameter.Value' -r)" >> $GITHUB_OUTPUT

      - name: Upload to S3
        run: aws s3 sync ./dist/ ${{ steps.parameters.outputs.bucket_name }} 1> /dev/null

#      - name: Invalidate CloudFront caches
#        run: aws cloudfront create-invalidation --distribution-id ${{ steps.parameters.outputs.cloudfront_id }}  --paths "/*" 1> /dev/null

      - name: Tag the build version
        run: |
          git tag "front-end-v${GITHUB_RUN_NUMBER}"
          git push origin "front-end-v${GITHUB_RUN_NUMBER}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: front-end-v${{ github.run_number }}
          release_name: front-end-v${{ github.run_number }}
          draft: false
          prerelease: false
