on:
  push:
    branches:
      - staging
      - master
    paths:
      - '/user/**'
  workflow_dispatch:

jobs:
  run-sonarQube-scan-on-user-service:
    if: github.ref == 'refs/heads/staging'
    uses: .github/workflows/back-end-sonarQube-scan.yml
    with:
      path: './user'
      service-name: 'user-service'
      sonarQube-token: ${{ secrets.SONAR_TOKEN_USER_SERVICE }}
      coverage-file: 'coverage-user.xml'

  deploy-user-service-staging:
    if: success() && github.ref == 'refs/heads/staging'
    needs: run-sonarQube-scan-on-user-service
    uses: .github/workflows/release-back-end-pipeline.yml
    with:
      path: '/user/**'
      service-name: 'user-service'
      environment: 'staging'

  deploy-user-service-master:
    if: github.ref == 'refs/heads/master'
    uses: .github/workflows/release-back-end-pipeline.yml
    with:
      path: '/user/**'
      service-name: 'user-service'
      environment: 'production'