on:
  push:
    branches:
      - staging
      - master
    paths:
      - '/card/**'
  workflow_dispatch:


jobs:
  run-sonarQube-scan-on-card-service:
    if: github.ref == 'refs/heads/staging'
    uses: .github/workflows/back-end-sonarQube-scan.yml
    with:
      path: './card'
      service-name: 'card-service'
      sonarQube-token: ${{ secrets.SONAR_TOKEN_CARD_SERVICE }}
      coverage-file: 'coverage-card.xml'

  deploy-card-service-staging:
    if: success() && github.ref == 'refs/heads/staging'
    needs: run-sonarQube-scan-on-card-service
    uses: .github/workflows/release-back-end-pipeline.yml
    with:
      path: '/card/**'
      service-name: 'card-service'
      environment: 'staging'

  deploy-card-service-master:
    if: github.ref == 'refs/heads/master'
    uses: .github/workflows/release-back-end-pipeline.yml
    with:
      path: '/card/**'
      service-name: 'card-service'
      environment: 'production'